return {
  'chentoast/marks.nvim',
  event = 'VeryLazy',
  opts = {
    default_mappings = false,
    builtin_marks = {},
    cyclic = true,
    force_write_shada = false,
    refresh_interval = 250,
    sign_priority = { lower = 10, upper = 15, builtin = 8, bookmark = 20 },
    excluded_filetypes = {},
    bookmark_0 = {
      sign = '⚑',
      virt_text = 'hello world',
      annotate = false,
    },
    mappings = {
      set = 'mx',
      set_next = 'm,',
      toggle = 'm;',
      next = 'm]',
      prev = 'm[',
      preview = 'm:',
      delete = 'mx',
      delete_line = 'm-',
      delete_bookmark = 'm=',
      delete_buf = 'm<space>',
    },
  },
}
